name: My first Workflow
on: [push]

jobs:
  job1:
    name: first-job
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        uses: actions/checkout@v4
      - name: second-step
        run: |
          echo "Hello from Ubuntu"
          env | sort
  job2:
    name: second-job
    runs-on: windows-latest
    needs: [job1]
    steps:
      - name: first-step
        uses: actions/checkout@v4
      - name: second-step
        run: "Get-childItem Env: | Sort-Object Name"
    
      
    
